"""Generated disabled-by-default WebMI sensor catalogue."""

from __future__ import annotations

# Generated from heliotherm-webmi-grouped-latest.json captured on 2026-05-19.
# Keep entries disabled by default; curate important points manually in descriptions.py.
GENERATED_SENSOR_POINTS: tuple[dict[str, str | None], ...] = (
    {
        "key": "diag_sp_329",
        "name": "Abssenkbetrieb Pumpe Absenkhys",
        "address": "webregler/sp/329/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_328",
        "name": "Abssenkbetrieb Pumpe Absenktemp",
        "address": "webregler/sp/328/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3338",
        "name": "Abtauung 2 Abt Ende Kond",
        "address": "webregler/sp/3338/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3387",
        "name": "Abtauung 2 Abtdiff bei 7 deg C",
        "address": "webregler/sp/3387/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3148",
        "name": "Abtauung 2 Abtdiff bei minus 15 deg C",
        "address": "webregler/sp/3148/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3302",
        "name": "Abtauung 2 Aktueller Wert",
        "address": "webregler/sp/3302/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3197",
        "name": "Abtauung 2 Durchfluss min",
        "address": "webregler/sp/3197/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3198",
        "name": "Abtauung 2 Ex V Start ND",
        "address": "webregler/sp/3198/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3195",
        "name": "Abtauung 2 RLT min",
        "address": "webregler/sp/3195/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3382",
        "name": "Abtauung 2 Schalthysterese",
        "address": "webregler/sp/3382/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3196",
        "name": "Abtauung 2 Weiter",
        "address": "webregler/sp/3196/value",
        "unit": 'K',
    },
    {
        "key": "diag_mp_261",
        "name": "Abtauung 2 Zeitverz EQP",
        "address": "webregler/mp/261/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3146",
        "name": "Abtauung 3 Abt Standzeit",
        "address": "webregler/sp/3146/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3255",
        "name": "Abtauung 3 Abtauung",
        "address": "webregler/sp/3255/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3337",
        "name": "Abtauung 3 letzte Laufzeit",
        "address": "webregler/sp/3337/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3140",
        "name": "Abtauung Abtaufreigabe",
        "address": "webregler/sp/3140/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3143",
        "name": "Abtauung Luft Ein temp",
        "address": "webregler/sp/3143/value",
        "unit": 'min',
    },
    {
        "key": "diag_sp_3384",
        "name": "Abtauung Min Laufzeit",
        "address": "webregler/sp/3384/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3142",
        "name": "Abtauung Verzoegerungszeit",
        "address": "webregler/sp/3142/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3383",
        "name": "Abtauung Vorl Zeit",
        "address": "webregler/sp/3383/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3326",
        "name": "Abtauung Weiter",
        "address": "webregler/sp/3326/value",
        "unit": 'min',
    },
    {
        "key": "diag_sp_3145",
        "name": "Abtauung max Abtauzeit",
        "address": "webregler/sp/3145/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3181",
        "name": "Ausheizen AH RL Endtemp",
        "address": "webregler/sp/3181/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3182",
        "name": "Ausheizen AH RL Zieltemp",
        "address": "webregler/sp/3182/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3447",
        "name": "Aussentemp Temp",
        "address": "webregler/sp/3447/value",
        "unit": 'min',
    },
    {
        "key": "diag_sp_3180",
        "name": "BSZ 2 Stufe Gesamt",
        "address": "webregler/sp/3180/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3177",
        "name": "BSZ 2 Stufe Heizbetrieb",
        "address": "webregler/sp/3177/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3178",
        "name": "BSZ 2 Stufe Schaltimpulse",
        "address": "webregler/sp/3178/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3176",
        "name": "BSZ 2 Stufe WW Betrieb",
        "address": "webregler/sp/3176/value",
        "unit": 'h',
    },
    {
        "key": "diag_mp_265",
        "name": "BSZ Pumpen 2 Mischer 1 2",
        "address": "webregler/mp/265/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3279",
        "name": "Betriebsstunden BSZ Pumpen 2 Schaltimpulse SP3279",
        "address": "webregler/sp/3279/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3282",
        "name": "Betriebsstunden BSZ Pumpen 2 Schaltimpulse SP3282",
        "address": "webregler/sp/3282/value",
        "unit": None,
    },
    {
        "key": "diag_mp_271",
        "name": "BSZ Pumpen 2 Solar 1 2",
        "address": "webregler/mp/271/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3277",
        "name": "BSZ Pumpen 2 id 40",
        "address": "webregler/sp/3277/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3280",
        "name": "BSZ Pumpen 2 id 43",
        "address": "webregler/sp/3280/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3165",
        "name": "BSZ Pumpen Brauchw pump",
        "address": "webregler/sp/3165/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3167",
        "name": "BSZ Pumpen EQ Pumpe",
        "address": "webregler/sp/3167/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3155",
        "name": "Betriebsstunden BSZ Pumpen Schaltimpulse SP3155",
        "address": "webregler/sp/3155/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3162",
        "name": "Betriebsstunden BSZ Pumpen Schaltimpulse SP3162",
        "address": "webregler/sp/3162/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3164",
        "name": "Betriebsstunden BSZ Pumpen Schaltimpulse SP3164",
        "address": "webregler/sp/3164/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3168",
        "name": "Betriebsstunden BSZ Pumpen Schaltimpulse SP3168",
        "address": "webregler/sp/3168/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3170",
        "name": "BSZ Pumpen Weiter",
        "address": "webregler/sp/3170/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3153",
        "name": "BSZ Pumpen Zirk pump",
        "address": "webregler/sp/3153/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3172",
        "name": "BSZ Verdichter Gesamt",
        "address": "webregler/sp/3172/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3171",
        "name": "BSZ Verdichter Heizbetrieb",
        "address": "webregler/sp/3171/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3397",
        "name": "BSZ Verdichter Jahr 1",
        "address": "webregler/sp/3397/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3173",
        "name": "BSZ Verdichter Jahr 2",
        "address": "webregler/sp/3173/value",
        "unit": 'h',
    },
    {
        "key": "diag_sp_3398",
        "name": "BSZ Verdichter WW Betrieb",
        "address": "webregler/sp/3398/value",
        "unit": None,
    },
    {
        "key": "diag_sp_339",
        "name": "Brauchwasserpumpe Ein",
        "address": "webregler/sp/339/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3300",
        "name": "Brauchwasserpumpe Nachl Zeit s",
        "address": "webregler/sp/3300/value",
        "unit": None,
    },
    {
        "key": "diag_sp_338",
        "name": "Brauchwasserpumpe Zustand",
        "address": "webregler/sp/338/value",
        "unit": 's',
    },
    {
        "key": "diag_mp_226",
        "name": "Carterheizung Ein",
        "address": "webregler/mp/226/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3193",
        "name": "Durchflussmin Aktueller Wert",
        "address": "webregler/sp/3193/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3190",
        "name": "Durchflussmin Anzahl 24 h",
        "address": "webregler/sp/3190/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3191",
        "name": "Durchflussmin Einschaltverzoegerung",
        "address": "webregler/sp/3191/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3192",
        "name": "Durchflussmin Schalthysterese",
        "address": "webregler/sp/3192/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3194",
        "name": "Durchflussmin Verzoegerungszeit",
        "address": "webregler/sp/3194/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_398",
        "name": "EQ Motorschutz Anzahl 24 h",
        "address": "webregler/sp/398/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_397",
        "name": "EQ Motorschutz Einschaltverzoegerung",
        "address": "webregler/sp/397/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_399",
        "name": "EQ Motorschutz Verzoegerungszeit",
        "address": "webregler/sp/399/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_341",
        "name": "EQ Pumpe Ein",
        "address": "webregler/sp/341/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_340",
        "name": "EQ Pumpe Vorl Zeit",
        "address": "webregler/sp/340/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3128",
        "name": "EQ Spreizung Aktueller Wert",
        "address": "webregler/sp/3128/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3125",
        "name": "EQ Spreizung Anzahl 24 h",
        "address": "webregler/sp/3125/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3126",
        "name": "EQ Spreizung Einschaltverzoegerung",
        "address": "webregler/sp/3126/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3127",
        "name": "EQ Spreizung Schalthysterese",
        "address": "webregler/sp/3127/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3129",
        "name": "EQ Spreizung Verzoegerungszeit",
        "address": "webregler/sp/3129/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3133",
        "name": "EQ Unterschreitung Aktueller Wert",
        "address": "webregler/sp/3133/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3130",
        "name": "EQ Unterschreitung Anzahl 24 h",
        "address": "webregler/sp/3130/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3131",
        "name": "EQ Unterschreitung Einschaltverzoegerung",
        "address": "webregler/sp/3131/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3132",
        "name": "EQ Unterschreitung Schalthysterese",
        "address": "webregler/sp/3132/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3134",
        "name": "EQ Unterschreitung Verzoegerungszeit",
        "address": "webregler/sp/3134/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3312",
        "name": "EQA 02 Invertiert",
        "address": "webregler/sp/3312/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3313",
        "name": "EQA 02 Vorregelwert",
        "address": "webregler/sp/3313/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3430",
        "name": "EQA 02 Vorregelzeit",
        "address": "webregler/sp/3430/value",
        "unit": None,
    },
    {
        "key": "diag_mp_248",
        "name": "EQA 02 Weiter",
        "address": "webregler/mp/248/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3393",
        "name": "EQA 02 n bei 18 deg C",
        "address": "webregler/sp/3393/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3314",
        "name": "EQA 02 n bei WW 18 deg C",
        "address": "webregler/sp/3314/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3394",
        "name": "EQA 02 n bei minus 15 deg C",
        "address": "webregler/sp/3394/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3449",
        "name": "EQA 022 KUE D Tv",
        "address": "webregler/sp/3449/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3448",
        "name": "EQA 022 KUE I Tn",
        "address": "webregler/sp/3448/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3451",
        "name": "EQA 022 KUE P Kp",
        "address": "webregler/sp/3451/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3450",
        "name": "EQA 022 Maxwert KUE",
        "address": "webregler/sp/3450/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3353",
        "name": "EQA 022 Minwert KUE",
        "address": "webregler/sp/3353/value",
        "unit": 'percent',
    },
    {
        "key": "diag_mp_288",
        "name": "Energiezaehler WMZ Durchfluss",
        "address": "webregler/mp/288/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3336",
        "name": "Exp Ventil Handwert",
        "address": "webregler/sp/3336/value",
        "unit": 'ms',
    },
    {
        "key": "diag_sp_3406",
        "name": "Ext Anforderung Ein",
        "address": "webregler/sp/3406/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3405",
        "name": "Ext Anforderung Nein",
        "address": "webregler/sp/3405/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3306",
        "name": "Ext Anforderung RLT max",
        "address": "webregler/sp/3306/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_389",
        "name": "FW System FWS D Tn",
        "address": "webregler/sp/389/value",
        "unit": None,
    },
    {
        "key": "diag_mp_2103",
        "name": "FW System FWS I Tv",
        "address": "webregler/mp/2103/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_392",
        "name": "FW System FWS Kp",
        "address": "webregler/sp/392/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_390",
        "name": "FW System Maxwert",
        "address": "webregler/sp/390/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_388",
        "name": "FW System Minwert",
        "address": "webregler/sp/388/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_393",
        "name": "FW System Stroemungswaechter",
        "address": "webregler/sp/393/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_391",
        "name": "FW System Triac FWS Pumpe",
        "address": "webregler/sp/391/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_387",
        "name": "FW System Zieltemp",
        "address": "webregler/sp/387/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3200",
        "name": "Mischer1 Grundbedienung HKR",
        "address": "webregler/sp/3200/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3244",
        "name": "Mischer2 Grundbedienung HKR",
        "address": "webregler/sp/3244/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3223",
        "name": "Grundbedienung RLT",
        "address": "webregler/sp/3223/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_395",
        "name": "HD Schalter Anzahl 24 h",
        "address": "webregler/sp/395/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_394",
        "name": "HD Schalter Einschaltverzoegerung",
        "address": "webregler/sp/394/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_396",
        "name": "HD Schalter Verzoegerungszeit",
        "address": "webregler/sp/396/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_315",
        "name": "Gesamtdaten HG Sollwert HG Solldiff SP315",
        "address": "webregler/sp/315/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_316",
        "name": "Gesamtdaten HG Sollwert HG Solldiff SP316",
        "address": "webregler/sp/316/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_318",
        "name": "HG Sollwert id 16",
        "address": "webregler/sp/318/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_317",
        "name": "HG Sollwert id 4",
        "address": "webregler/sp/317/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3358",
        "name": "HKPA 01 D Tv",
        "address": "webregler/sp/3358/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3357",
        "name": "HKPA 01 I Tn",
        "address": "webregler/sp/3357/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3391",
        "name": "HKPA 01 Invertiert",
        "address": "webregler/sp/3391/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3429",
        "name": "HKPA 01 Minwert",
        "address": "webregler/sp/3429/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3356",
        "name": "HKPA 01 P Kp",
        "address": "webregler/sp/3356/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3392",
        "name": "HKPA 01 Vorregelwert",
        "address": "webregler/sp/3392/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3359",
        "name": "HKPA 01 Vorregelzeit",
        "address": "webregler/sp/3359/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3369",
        "name": "HKPA 01 Zieltemp",
        "address": "webregler/sp/3369/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3113",
        "name": "Heissgasmax Aktueller Wert",
        "address": "webregler/sp/3113/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3110",
        "name": "Heissgasmax Anzahl 24 h",
        "address": "webregler/sp/3110/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3111",
        "name": "Heissgasmax Einschaltverzoegerung",
        "address": "webregler/sp/3111/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3112",
        "name": "Heissgasmax Schalthysterese",
        "address": "webregler/sp/3112/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3114",
        "name": "Heissgasmax Verzoegerungszeit",
        "address": "webregler/sp/3114/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_336",
        "name": "Heizkreispumpe 2 Handbetrieb",
        "address": "webregler/sp/336/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_335",
        "name": "Heizkreispumpe 2 Nachl Zeit",
        "address": "webregler/sp/335/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_333",
        "name": "Heizkreispumpe 2 Puls ein aus",
        "address": "webregler/sp/333/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_334",
        "name": "Heizkreispumpe 2 id 29",
        "address": "webregler/sp/334/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3459",
        "name": "Heizkreispumpe Aus",
        "address": "webregler/sp/3459/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3295",
        "name": "Heizkreispumpe WW Anf abhae",
        "address": "webregler/sp/3295/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3232",
        "name": "Mischer2 Heizkurve Heizgrenze",
        "address": "webregler/sp/3232/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_380",
        "name": "Heizkreis Heizkurve Heizgrenze",
        "address": "webregler/sp/380/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3210",
        "name": "Mischer1 Heizkurve RLsoll Null bei 0 deg C",
        "address": "webregler/sp/3210/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3234",
        "name": "Mischer2 Heizkurve RLsoll Null bei 0 deg C",
        "address": "webregler/sp/3234/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_382",
        "name": "Heizkreis Heizkurve RLsoll Null bei 0 deg C",
        "address": "webregler/sp/382/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3209",
        "name": "Mischer1 Heizkurve RLsoll oben bei 15 deg C",
        "address": "webregler/sp/3209/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3228",
        "name": "Mischer2 Heizkurve RLsoll oben bei 15 deg C",
        "address": "webregler/sp/3228/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3233",
        "name": "Mischer2 Heizkurve RLsoll unten bei minus 15 deg C",
        "address": "webregler/sp/3233/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3211",
        "name": "Mischer1 Heizkurve RLsoll unten minus 15 deg C",
        "address": "webregler/sp/3211/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_381",
        "name": "Heizkreis Heizkurve RLsoll unten minus 15 deg C",
        "address": "webregler/sp/381/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3440",
        "name": "IO Erweiterung 2 Abt druckdiff",
        "address": "webregler/sp/3440/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3442",
        "name": "IO Erweiterung 2 EXV D Tv",
        "address": "webregler/sp/3442/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3439",
        "name": "IO Erweiterung 2 EXV I Tn",
        "address": "webregler/sp/3439/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3349",
        "name": "IO Erweiterung 2 EXV P Kp",
        "address": "webregler/sp/3349/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3441",
        "name": "IO Erweiterung 2 Solldiff Saugg",
        "address": "webregler/sp/3441/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3446",
        "name": "IO Erweiterung 2 Vorregelwert",
        "address": "webregler/sp/3446/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3443",
        "name": "IO Erweiterung 2 Vorregelzeit",
        "address": "webregler/sp/3443/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3423",
        "name": "IO Erweiterung Druckdiff",
        "address": "webregler/sp/3423/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3419",
        "name": "IO Erweiterung EXV D Tv",
        "address": "webregler/sp/3419/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3427",
        "name": "IO Erweiterung EXV P Kp",
        "address": "webregler/sp/3427/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3422",
        "name": "IO Erweiterung Handwert",
        "address": "webregler/sp/3422/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3420",
        "name": "IO Erweiterung Minwert",
        "address": "webregler/sp/3420/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3421",
        "name": "IO Erweiterung Vorregelwert",
        "address": "webregler/sp/3421/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3426",
        "name": "IO Erweiterung Vorregelzeit",
        "address": "webregler/sp/3426/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3103",
        "name": "Kondensat Druck Aktueller Wert",
        "address": "webregler/sp/3103/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3100",
        "name": "Kondensat Druck Anzahl 24 h",
        "address": "webregler/sp/3100/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3101",
        "name": "Kondensat Druck Einschaltverzoegerung",
        "address": "webregler/sp/3101/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3102",
        "name": "Kondensat Druck Schalthysterese",
        "address": "webregler/sp/3102/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3104",
        "name": "Kondensat Druck Verzoegerungszeit",
        "address": "webregler/sp/3104/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3138",
        "name": "Kondensat Temp Aktueller Wert",
        "address": "webregler/sp/3138/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3135",
        "name": "Kondensat Temp Anzahl 24 h",
        "address": "webregler/sp/3135/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3136",
        "name": "Kondensat Temp Einschaltverzoegerung",
        "address": "webregler/sp/3136/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3137",
        "name": "Kondensat Temp Schalthysterese",
        "address": "webregler/sp/3137/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3139",
        "name": "Kondensat Temp Verzoegerungszeit",
        "address": "webregler/sp/3139/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_33",
        "name": "Main 2 2 Stufe AH ZP",
        "address": "webregler/sp/33/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3403",
        "name": "Main 2 2 Stufe Stoerung",
        "address": "webregler/sp/3403/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3402",
        "name": "Main 2 Aus",
        "address": "webregler/sp/3402/value",
        "unit": None,
    },
    {
        "key": "diag_sp_352",
        "name": "WNA Main 2 Ein SP352",
        "address": "webregler/sp/352/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_353",
        "name": "WNA Main 2 Ein SP353",
        "address": "webregler/sp/353/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3458",
        "name": "Main 2 IO Erweiterung",
        "address": "webregler/sp/3458/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3428",
        "name": "Main 2 KKM Erweiter",
        "address": "webregler/sp/3428/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3315",
        "name": "Main 2 Kuehlen",
        "address": "webregler/sp/3315/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3264",
        "name": "Main 2 Weiter",
        "address": "webregler/sp/3264/value",
        "unit": None,
    },
    {
        "key": "diag_sp_38",
        "name": "Main 3 Energiezaehler",
        "address": "webregler/sp/38/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3263",
        "name": "Main 3 Zuruecksetzen",
        "address": "webregler/sp/3263/value",
        "unit": None,
    },
    {
        "key": "diag_sp_37",
        "name": "Main Ext Anforder",
        "address": "webregler/sp/37/value",
        "unit": None,
    },
    {
        "key": "diag_sp_36",
        "name": "Main Ext Vorrang",
        "address": "webregler/sp/36/value",
        "unit": None,
    },
    {
        "key": "diag_sp_34",
        "name": "Main FW Syst",
        "address": "webregler/sp/34/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3249",
        "name": "Main HKR RLT min",
        "address": "webregler/sp/3249/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3175",
        "name": "Main Kuehlen Soll",
        "address": "webregler/sp/3175/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3250",
        "name": "Main MKR 1 RLT min",
        "address": "webregler/sp/3250/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3251",
        "name": "Main MKR 2 RLT min",
        "address": "webregler/sp/3251/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3147",
        "name": "Main Mischer 1",
        "address": "webregler/sp/3147/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3267",
        "name": "Main Mischer 2",
        "address": "webregler/sp/3267/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3199",
        "name": "Main Puffertyp",
        "address": "webregler/sp/3199/value",
        "unit": None,
    },
    {
        "key": "diag_mcg_webclientversion",
        "name": "Main RCG Version",
        "address": "mcg/data/webclientversion",
        "unit": None,
    },
    {
        "key": "diag_sp_35",
        "name": "Main Solaranlage",
        "address": "webregler/sp/35/value",
        "unit": None,
    },
    {
        "key": "diag_sp_314",
        "name": "Main Stoerung quittieren",
        "address": "webregler/sp/314/value",
        "unit": None,
    },
    {
        "key": "diag_mcg_srvversion",
        "name": "Main Visualisierung Version",
        "address": "mcg/data/srvVersion",
        "unit": None,
    },
    {
        "key": "diag_sp_3141",
        "name": "Main Vollversion",
        "address": "webregler/sp/3141/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3271",
        "name": "Main WW Vorrang",
        "address": "webregler/sp/3271/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3222",
        "name": "Main Weiter",
        "address": "webregler/sp/3222/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3286",
        "name": "Main Zaehlerreset",
        "address": "webregler/sp/3286/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3243",
        "name": "Mischer 2 Mi Sollpos",
        "address": "webregler/sp/3243/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3320",
        "name": "Mischerpumpe 2 Aus",
        "address": "webregler/sp/3320/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3299",
        "name": "Mischerpumpe 2 Betriebsart",
        "address": "webregler/sp/3299/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3317",
        "name": "Mischerpumpe 2 EVU Sperre",
        "address": "webregler/sp/3317/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3390",
        "name": "Mischerpumpe 2 Handwert",
        "address": "webregler/sp/3390/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3316",
        "name": "Mischerpumpe 2 Kuehlen",
        "address": "webregler/sp/3316/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3319",
        "name": "Mischerpumpe 2 Modus",
        "address": "webregler/sp/3319/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3298",
        "name": "Mischerpumpe 2 Nachl Zeit",
        "address": "webregler/sp/3298/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3318",
        "name": "Mischerpumpe 2 Vorl Zeit",
        "address": "webregler/sp/3318/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3389",
        "name": "Mischerpumpe Betriebsart",
        "address": "webregler/sp/3389/value",
        "unit": None,
    },
    {
        "key": "diag_sp_348",
        "name": "Mischerpumpe EVU Sperre",
        "address": "webregler/sp/348/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_344",
        "name": "Mischerpumpe Handwert",
        "address": "webregler/sp/344/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_345",
        "name": "Mischerpumpe Kuehlen",
        "address": "webregler/sp/345/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_347",
        "name": "Mischerpumpe Modus",
        "address": "webregler/sp/347/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3296",
        "name": "Mischerpumpe Nachl Zeit",
        "address": "webregler/sp/3296/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3297",
        "name": "Mischerpumpe Puls ein aus",
        "address": "webregler/sp/3297/value",
        "unit": None,
    },
    {
        "key": "diag_sp_346",
        "name": "Mischerpumpe Vorl Zeit",
        "address": "webregler/sp/346/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3217",
        "name": "Mischer1 Parameter 2 MIS D Tv",
        "address": "webregler/sp/3217/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3241",
        "name": "Mischer2 Parameter 2 MIS D Tv",
        "address": "webregler/sp/3241/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3216",
        "name": "Mischer1 Parameter 2 MIS I Tn",
        "address": "webregler/sp/3216/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3239",
        "name": "Mischer2 Parameter 2 MIS I Tn",
        "address": "webregler/sp/3239/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3218",
        "name": "Mischer1 Parameter 2 Minwert",
        "address": "webregler/sp/3218/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3240",
        "name": "Mischer2 Parameter 2 Minwert",
        "address": "webregler/sp/3240/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3206",
        "name": "Mischer1 Parameter AT Hys",
        "address": "webregler/sp/3206/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3227",
        "name": "Mischer2 Parameter AT Hys",
        "address": "webregler/sp/3227/value",
        "unit": None,
    },
    {
        "key": "diag_sp_373",
        "name": "Heizkreis Parameter AT Hys",
        "address": "webregler/sp/373/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3214",
        "name": "Mischer1 Parameter DPR Schalthysterese",
        "address": "webregler/sp/3214/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3229",
        "name": "Mischer2 Parameter DPR Schalthysterese",
        "address": "webregler/sp/3229/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3213",
        "name": "Mischer1 Parameter DPR Sollhys",
        "address": "webregler/sp/3213/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_322",
        "name": "Gesamtdaten Parameter Druckdiff",
        "address": "webregler/sp/322/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_321",
        "name": "Gesamtdaten Parameter EXV D Tv",
        "address": "webregler/sp/321/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3310",
        "name": "Gesamtdaten Parameter EXV I Tn",
        "address": "webregler/sp/3310/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_324",
        "name": "Gesamtdaten Parameter EXV P Kp",
        "address": "webregler/sp/324/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_326",
        "name": "Gesamtdaten Parameter Einspritzzeit",
        "address": "webregler/sp/326/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3149",
        "name": "Effizienz Parameter Energiewert",
        "address": "webregler/sp/3149/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3400",
        "name": "Effizienz Parameter Faktor WMZ",
        "address": "webregler/sp/3400/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_323",
        "name": "Gesamtdaten Parameter Grenzwert",
        "address": "webregler/sp/323/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_370",
        "name": "Warmwasser Parameter Grenzwert 2 Stufe",
        "address": "webregler/sp/370/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3347",
        "name": "Warmwasser Parameter Grenzwert Enthitzer",
        "address": "webregler/sp/3347/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_386",
        "name": "Warmwasser Parameter Hys Min",
        "address": "webregler/sp/386/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3339",
        "name": "Warmwasser Parameter Hys Norm",
        "address": "webregler/sp/3339/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3437",
        "name": "Heizkreis Parameter Hys bei SP3437",
        "address": "webregler/sp/3437/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_374",
        "name": "Heizkreis Parameter Hys bei SP374",
        "address": "webregler/sp/374/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3215",
        "name": "Mischer1 Parameter MIS P Kp",
        "address": "webregler/sp/3215/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3231",
        "name": "Mischer2 Parameter MIS P Kp",
        "address": "webregler/sp/3231/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_320",
        "name": "Gesamtdaten Parameter Minwert",
        "address": "webregler/sp/320/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_319",
        "name": "Gesamtdaten Parameter Offset",
        "address": "webregler/sp/319/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3355",
        "name": "Mischer2 Parameter Offset",
        "address": "webregler/sp/3355/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3453",
        "name": "Mischer1 Parameter Offset",
        "address": "webregler/sp/3453/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_377",
        "name": "Heizkreis Parameter Offset",
        "address": "webregler/sp/377/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3208",
        "name": "Mischer1 Parameter RLT Max",
        "address": "webregler/sp/3208/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3236",
        "name": "Mischer2 Parameter RLT Max",
        "address": "webregler/sp/3236/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_379",
        "name": "Heizkreis Parameter RLT Max",
        "address": "webregler/sp/379/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3204",
        "name": "Mischer1 Parameter Soll Raum Verst",
        "address": "webregler/sp/3204/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3351",
        "name": "Heizkreis Parameter Sollhys",
        "address": "webregler/sp/3351/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3455",
        "name": "Mischer2 Parameter Sollhys",
        "address": "webregler/sp/3455/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3237",
        "name": "Mischer2 Parameter Spreizung",
        "address": "webregler/sp/3237/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3150",
        "name": "Effizienz Parameter Verdichter",
        "address": "webregler/sp/3150/value",
        "unit": None,
    },
    {
        "key": "diag_sp_327",
        "name": "Gesamtdaten Parameter Vorregelwert",
        "address": "webregler/sp/327/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3309",
        "name": "Gesamtdaten Parameter Vorregelzeit",
        "address": "webregler/sp/3309/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_384",
        "name": "Warmwasser Parameter WW Max",
        "address": "webregler/sp/384/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3238",
        "name": "Mischer2 Parameter Weiter",
        "address": "webregler/sp/3238/value",
        "unit": None,
    },
    {
        "key": "diag_sp_375",
        "name": "Heizkreis Parameter id 17",
        "address": "webregler/sp/375/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3256",
        "name": "Heizkreis Parameter id 20",
        "address": "webregler/sp/3256/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3273",
        "name": "Prameter Hys Min",
        "address": "webregler/sp/3273/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3152",
        "name": "Prameter Hys Norm",
        "address": "webregler/sp/3152/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3332",
        "name": "Prameter Maxwert",
        "address": "webregler/sp/3332/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3272",
        "name": "Prameter Minwert",
        "address": "webregler/sp/3272/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3274",
        "name": "Prameter Schalthysterese",
        "address": "webregler/sp/3274/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_343",
        "name": "Pufferpumpe Ein",
        "address": "webregler/sp/343/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3301",
        "name": "Pufferpumpe Nachl Zeit",
        "address": "webregler/sp/3301/value",
        "unit": None,
    },
    {
        "key": "diag_sp_342",
        "name": "Pufferpumpe Zustand",
        "address": "webregler/sp/342/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3305",
        "name": "Pumpeext Ein",
        "address": "webregler/sp/3305/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3304",
        "name": "Pumpeext Nachl Zeit",
        "address": "webregler/sp/3304/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3303",
        "name": "Pumpeext Zustand",
        "address": "webregler/sp/3303/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3262",
        "name": "Regelabw Aktueller Wert",
        "address": "webregler/sp/3262/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3258",
        "name": "Regelabw Anzahl 24 h",
        "address": "webregler/sp/3258/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3259",
        "name": "Regelabw Einschaltverzoegerung",
        "address": "webregler/sp/3259/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3260",
        "name": "Regelabw Grenzwert",
        "address": "webregler/sp/3260/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3261",
        "name": "Regelabw Schalthysterese",
        "address": "webregler/sp/3261/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3307",
        "name": "Sauggas min Anzahl 24 h",
        "address": "webregler/sp/3307/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3124",
        "name": "Sauggas min Einschaltverzoegerung",
        "address": "webregler/sp/3124/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3123",
        "name": "Sauggas min Fehlerverzoegerung",
        "address": "webregler/sp/3123/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3386",
        "name": "Sauggas min Grenzwert",
        "address": "webregler/sp/3386/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3121",
        "name": "Sauggas min Verzoegerungszeit",
        "address": "webregler/sp/3121/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3122",
        "name": "Sauggas min aktueller Wert",
        "address": "webregler/sp/3122/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3334",
        "name": "Solarpumpe Ein",
        "address": "webregler/sp/3334/value",
        "unit": 'min',
    },
    {
        "key": "diag_sp_3276",
        "name": "Solarpumpe Haltezeit",
        "address": "webregler/sp/3276/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3275",
        "name": "Solarpumpe Handwert",
        "address": "webregler/sp/3275/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3333",
        "name": "Solarpumpe Puls aus",
        "address": "webregler/sp/3333/value",
        "unit": 'min',
    },
    {
        "key": "diag_sp_3203",
        "name": "Mischer1 Sollwert Absenktemp",
        "address": "webregler/sp/3203/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3230",
        "name": "Mischer2 Sollwert Absenktemp",
        "address": "webregler/sp/3230/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_369",
        "name": "Heizkreis Sollwert Absenktemp",
        "address": "webregler/sp/369/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3285",
        "name": "Solaranlage Sollwert Anforderung",
        "address": "webregler/sp/3285/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3202",
        "name": "Mischer1 Sollwert Aufheiztemp",
        "address": "webregler/sp/3202/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_371",
        "name": "Heizkreis Sollwert Aufheiztemp",
        "address": "webregler/sp/371/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_378",
        "name": "Heizkreis Sollwert RLT min",
        "address": "webregler/sp/378/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3226",
        "name": "Mischer2 Sollwert Raum Soll",
        "address": "webregler/sp/3226/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_372",
        "name": "Heizkreis Sollwert Raum Soll",
        "address": "webregler/sp/372/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3283",
        "name": "Solaranlage Sollwert Solar KT 1",
        "address": "webregler/sp/3283/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3207",
        "name": "Mischer1 Sollwert VLT min",
        "address": "webregler/sp/3207/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3225",
        "name": "Mischer2 Sollwert VLT min",
        "address": "webregler/sp/3225/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_385",
        "name": "Warmwasser Sollwert WW Min",
        "address": "webregler/sp/385/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3284",
        "name": "Solaranlage Sollwert WW Norm",
        "address": "webregler/sp/3284/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_383",
        "name": "Warmwasser Sollwert WW Norm",
        "address": "webregler/sp/383/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_mp_220",
        "name": "Verdampf Druck Aktueller Wert",
        "address": "webregler/mp/220/value",
        "unit": 'bar',
    },
    {
        "key": "diag_mp_212",
        "name": "Temp 2 Mischer 1 2 VLT",
        "address": "webregler/mp/212/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_mp_213",
        "name": "Temp 2 Sauggastemp",
        "address": "webregler/mp/213/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_mp_221",
        "name": "Kondensat Druck Aktueller Wert",
        "address": "webregler/mp/221/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3385",
        "name": "Triac 2 Stufe Istwert",
        "address": "webregler/sp/3385/value",
        "unit": None,
    },
    {
        "key": "diag_mp_250",
        "name": "Triac FWSPumpe Istwert",
        "address": "webregler/mp/250/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3368",
        "name": "VD Mod 2 Abtauung min max",
        "address": "webregler/sp/3368/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3246",
        "name": "VD Mod 2 Ext Anf n 15 deg C",
        "address": "webregler/sp/3246/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3311",
        "name": "VD Mod 2 Oel Rueckf GW",
        "address": "webregler/sp/3311/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3248",
        "name": "VD Mod 2 n bei 0 deg C",
        "address": "webregler/sp/3248/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3346",
        "name": "VD Mod 2 n bei 15 deg C",
        "address": "webregler/sp/3346/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3460",
        "name": "VD Mod 2 n bei Kuehlen",
        "address": "webregler/sp/3460/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3367",
        "name": "VD Mod 2 n bei minus 15 deg C",
        "address": "webregler/sp/3367/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3457",
        "name": "VD Mod Current",
        "address": "webregler/sp/3457/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3416",
        "name": "VD Mod GTO Temp",
        "address": "webregler/sp/3416/value",
        "unit": 'percent',
    },
    {
        "key": "diag_mp_296",
        "name": "VD Mod Regelabw",
        "address": "webregler/mp/296/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3345",
        "name": "VD Mod Sollwert",
        "address": "webregler/sp/3345/value",
        "unit": 'percent',
    },
    {
        "key": "diag_mp_294",
        "name": "VD Mod Start Drehzahl",
        "address": "webregler/mp/294/value",
        "unit": 'A',
    },
    {
        "key": "diag_sp_3335",
        "name": "VD Mod Start Drehzahl 2",
        "address": "webregler/sp/3335/value",
        "unit": 'percent',
    },
    {
        "key": "diag_sp_3417",
        "name": "VD Mod Verzoegerungszeit",
        "address": "webregler/sp/3417/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3308",
        "name": "Verdampf Druck Aktueller Wert",
        "address": "webregler/sp/3308/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3105",
        "name": "Verdampf Druck Anzahl 24 h",
        "address": "webregler/sp/3105/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3445",
        "name": "Verdampf Druck Einschaltverzoegerung",
        "address": "webregler/sp/3445/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3107",
        "name": "Verdampf Druck Schalthysterese",
        "address": "webregler/sp/3107/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3106",
        "name": "Sicherheitskette Verdampf Druck Verzoegerungszeit SP3106",
        "address": "webregler/sp/3106/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3444",
        "name": "Sicherheitskette Verdampf Druck Verzoegerungszeit SP3444",
        "address": "webregler/sp/3444/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3108",
        "name": "Verdampf Druck id 13",
        "address": "webregler/sp/3108/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3109",
        "name": "Verdampf Druck id 16",
        "address": "webregler/sp/3109/value",
        "unit": 'x',
    },
    {
        "key": "diag_sp_3292",
        "name": "Verdichter Aus",
        "address": "webregler/sp/3292/value",
        "unit": 'K',
    },
    {
        "key": "diag_sp_3344",
        "name": "Verdichter Druckdiff",
        "address": "webregler/sp/3344/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_312",
        "name": "Verdichter Einschaltverzoegerung",
        "address": "webregler/sp/312/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3235",
        "name": "Verdichter Verd Oels diff",
        "address": "webregler/sp/3235/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_349",
        "name": "WW Zirkulation Nachl Zeit",
        "address": "webregler/sp/349/value",
        "unit": 's',
    },
    {
        "key": "diag_mp_238",
        "name": "WW Zirkulation Nein",
        "address": "webregler/mp/238/value",
        "unit": None,
    },
    {
        "key": "diag_sp_350",
        "name": "WW Zirkulation Schaltuhr",
        "address": "webregler/sp/350/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_351",
        "name": "WW Zirkulation Stroemungswaechter",
        "address": "webregler/sp/351/value",
        "unit": None,
    },
    {
        "key": "diag_sp_332",
        "name": "Wartungslauf Laufzeit",
        "address": "webregler/sp/332/value",
        "unit": '00',
    },
    {
        "key": "diag_sp_331",
        "name": "Wartungslauf Uhrzeit",
        "address": "webregler/sp/331/value",
        "unit": None,
    },
    {
        "key": "diag_sp_330",
        "name": "Wartungslauf Wochentag",
        "address": "webregler/sp/330/value",
        "unit": 's',
    },
    {
        "key": "diag_mcg_web_machinetype",
        "name": "Web Regler COM Speed",
        "address": "mcg/data/web/machineType",
        "unit": None,
    },
    {
        "key": "diag_mcg_web_serialnr",
        "name": "Web Regler Clear",
        "address": "mcg/data/web/serialnr",
        "unit": None,
    },
    {
        "key": "diag_sp_311",
        "name": "Web Regler RCG Stoerung Clear",
        "address": "webregler/sp/311/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3118",
        "name": "diff HD ND Aktueller Wert",
        "address": "webregler/sp/3118/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3115",
        "name": "diff HD ND Anzahl 24 h",
        "address": "webregler/sp/3115/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3116",
        "name": "diff HD ND Einschaltverzoegerung",
        "address": "webregler/sp/3116/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_3117",
        "name": "diff HD ND Schalthysterese",
        "address": "webregler/sp/3117/value",
        "unit": 's',
    },
    {
        "key": "diag_sp_3119",
        "name": "diff HD ND Verzoegerungszeit",
        "address": "webregler/sp/3119/value",
        "unit": 'x',
    },
)
