"""Generated disabled-by-default WebMI sensor catalogue."""

from __future__ import annotations

# Generated from heliotherm-webmi-grouped-latest.json captured on 2026-05-19.
# Keep entries disabled by default; curate important points manually in descriptions.py.
GENERATED_SENSOR_POINTS: tuple[dict[str, str | None], ...] = (
    {
        "key": "diag_mp_256",
        "name": "Infobox MP 256",
        "address": "webregler/mp/256/value",
        "unit": None,
    },
    {
        "key": "diag_mcg_errorlog",
        "name": "Landscape Alarm Fehlerlog",
        "address": "mcg/data/errorLog",
        "unit": None,
    },
    {
        "key": "diag_sp_314",
        "name": "Landscape Alarm SP 314",
        "address": "webregler/sp/314/value",
        "unit": None,
    },
    {
        "key": "diag_sp_313",
        "name": "Landscape Betriebsart SP 313",
        "address": "webregler/sp/313/value",
        "unit": None,
    },
    {
        "key": "diag_mp_252",
        "name": "Landscape Effizienz MP 252",
        "address": "webregler/mp/252/value",
        "unit": None,
    },
    {
        "key": "diag_mp_253",
        "name": "Landscape Effizienz MP 253",
        "address": "webregler/mp/253/value",
        "unit": None,
    },
    {
        "key": "diag_mp_254",
        "name": "Landscape Effizienz MP 254",
        "address": "webregler/mp/254/value",
        "unit": None,
    },
    {
        "key": "diag_mp_255",
        "name": "Landscape Effizienz MP 255",
        "address": "webregler/mp/255/value",
        "unit": None,
    },
    {
        "key": "diag_mp_275",
        "name": "Landscape Effizienz MP 275",
        "address": "webregler/mp/275/value",
        "unit": None,
    },
    {
        "key": "diag_mp_284",
        "name": "Landscape Effizienz MP 284",
        "address": "webregler/mp/284/value",
        "unit": None,
    },
    {
        "key": "diag_mp_292",
        "name": "Landscape Effizienz MP 292",
        "address": "webregler/mp/292/value",
        "unit": None,
    },
    {
        "key": "diag_mcg_web_time",
        "name": "Landscape Einstellungen Controller Zeit",
        "address": "mcg/data/web/time",
        "unit": None,
    },
    {
        "key": "diag_sp_310",
        "name": "Landscape Startseite SP 310",
        "address": "webregler/sp/310/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3175",
        "name": "Main Schnellwahl SP 3175",
        "address": "webregler/sp/3175/value",
        "unit": None,
    },
    {
        "key": "diag_mp_265",
        "name": "Service Betriebsstunden MP 265",
        "address": "webregler/mp/265/value",
        "unit": None,
    },
    {
        "key": "diag_mp_271",
        "name": "Service Betriebsstunden MP 271",
        "address": "webregler/mp/271/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3153",
        "name": "Service Betriebsstunden SP 3153",
        "address": "webregler/sp/3153/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3155",
        "name": "Service Betriebsstunden SP 3155",
        "address": "webregler/sp/3155/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3162",
        "name": "Service Betriebsstunden SP 3162",
        "address": "webregler/sp/3162/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3164",
        "name": "Service Betriebsstunden SP 3164",
        "address": "webregler/sp/3164/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3165",
        "name": "Service Betriebsstunden SP 3165",
        "address": "webregler/sp/3165/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3167",
        "name": "Service Betriebsstunden SP 3167",
        "address": "webregler/sp/3167/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3168",
        "name": "Service Betriebsstunden SP 3168",
        "address": "webregler/sp/3168/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3170",
        "name": "Service Betriebsstunden SP 3170",
        "address": "webregler/sp/3170/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3171",
        "name": "Service Betriebsstunden SP 3171",
        "address": "webregler/sp/3171/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3172",
        "name": "Service Betriebsstunden SP 3172",
        "address": "webregler/sp/3172/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3173",
        "name": "Service Betriebsstunden SP 3173",
        "address": "webregler/sp/3173/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3176",
        "name": "Service Betriebsstunden SP 3176",
        "address": "webregler/sp/3176/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3177",
        "name": "Service Betriebsstunden SP 3177",
        "address": "webregler/sp/3177/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3178",
        "name": "Service Betriebsstunden SP 3178",
        "address": "webregler/sp/3178/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3180",
        "name": "Service Betriebsstunden SP 3180",
        "address": "webregler/sp/3180/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3277",
        "name": "Service Betriebsstunden SP 3277",
        "address": "webregler/sp/3277/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3279",
        "name": "Service Betriebsstunden SP 3279",
        "address": "webregler/sp/3279/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3280",
        "name": "Service Betriebsstunden SP 3280",
        "address": "webregler/sp/3280/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3282",
        "name": "Service Betriebsstunden SP 3282",
        "address": "webregler/sp/3282/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3397",
        "name": "Service Betriebsstunden SP 3397",
        "address": "webregler/sp/3397/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3398",
        "name": "Service Betriebsstunden SP 3398",
        "address": "webregler/sp/3398/value",
        "unit": None,
    },
    {
        "key": "diag_mp_283",
        "name": "Service Effizienz MP 283",
        "address": "webregler/mp/283/value",
        "unit": None,
    },
    {
        "key": "diag_mp_285",
        "name": "Service Effizienz MP 285",
        "address": "webregler/mp/285/value",
        "unit": None,
    },
    {
        "key": "diag_mp_288",
        "name": "Service Effizienz MP 288",
        "address": "webregler/mp/288/value",
        "unit": None,
    },
    {
        "key": "diag_mp_289",
        "name": "Service Effizienz MP 289",
        "address": "webregler/mp/289/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3149",
        "name": "Service Effizienz SP 3149",
        "address": "webregler/sp/3149/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3150",
        "name": "Service Effizienz SP 3150",
        "address": "webregler/sp/3150/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3286",
        "name": "Service Effizienz SP 3286",
        "address": "webregler/sp/3286/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3400",
        "name": "Service Effizienz SP 3400",
        "address": "webregler/sp/3400/value",
        "unit": None,
    },
    {
        "key": "diag_mp_21",
        "name": "Service Gesamtdaten Hochdruck",
        "address": "webregler/mp/21/value",
        "unit": 'bar',
    },
    {
        "key": "diag_sp_348",
        "name": "Service Gesamtdaten MKR1 min Ruecklauftemperatur Kuehlen",
        "address": "webregler/sp/348/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_mp_223",
        "name": "Service Gesamtdaten MP 223",
        "address": "webregler/mp/223/value",
        "unit": None,
    },
    {
        "key": "diag_mp_224",
        "name": "Service Gesamtdaten MP 224",
        "address": "webregler/mp/224/value",
        "unit": None,
    },
    {
        "key": "diag_mp_225",
        "name": "Service Gesamtdaten MP 225",
        "address": "webregler/mp/225/value",
        "unit": None,
    },
    {
        "key": "diag_mp_226",
        "name": "Service Gesamtdaten MP 226",
        "address": "webregler/mp/226/value",
        "unit": None,
    },
    {
        "key": "diag_mp_227",
        "name": "Service Gesamtdaten MP 227",
        "address": "webregler/mp/227/value",
        "unit": None,
    },
    {
        "key": "diag_mp_228",
        "name": "Service Gesamtdaten MP 228",
        "address": "webregler/mp/228/value",
        "unit": None,
    },
    {
        "key": "diag_mp_229",
        "name": "Service Gesamtdaten MP 229",
        "address": "webregler/mp/229/value",
        "unit": None,
    },
    {
        "key": "diag_mp_230",
        "name": "Service Gesamtdaten MP 230",
        "address": "webregler/mp/230/value",
        "unit": None,
    },
    {
        "key": "diag_mp_231",
        "name": "Service Gesamtdaten MP 231",
        "address": "webregler/mp/231/value",
        "unit": None,
    },
    {
        "key": "diag_mp_232",
        "name": "Service Gesamtdaten MP 232",
        "address": "webregler/mp/232/value",
        "unit": None,
    },
    {
        "key": "diag_mp_233",
        "name": "Service Gesamtdaten MP 233",
        "address": "webregler/mp/233/value",
        "unit": None,
    },
    {
        "key": "diag_mp_234",
        "name": "Service Gesamtdaten MP 234",
        "address": "webregler/mp/234/value",
        "unit": None,
    },
    {
        "key": "diag_mp_235",
        "name": "Service Gesamtdaten MP 235",
        "address": "webregler/mp/235/value",
        "unit": None,
    },
    {
        "key": "diag_mp_236",
        "name": "Service Gesamtdaten MP 236",
        "address": "webregler/mp/236/value",
        "unit": None,
    },
    {
        "key": "diag_mp_237",
        "name": "Service Gesamtdaten MP 237",
        "address": "webregler/mp/237/value",
        "unit": None,
    },
    {
        "key": "diag_mp_240",
        "name": "Service Gesamtdaten MP 240",
        "address": "webregler/mp/240/value",
        "unit": None,
    },
    {
        "key": "diag_mp_245",
        "name": "Service Gesamtdaten MP 245",
        "address": "webregler/mp/245/value",
        "unit": None,
    },
    {
        "key": "diag_mp_248",
        "name": "Service Gesamtdaten MP 248",
        "address": "webregler/mp/248/value",
        "unit": None,
    },
    {
        "key": "diag_mp_249",
        "name": "Service Gesamtdaten MP 249",
        "address": "webregler/mp/249/value",
        "unit": None,
    },
    {
        "key": "diag_mp_250",
        "name": "Service Gesamtdaten MP 250",
        "address": "webregler/mp/250/value",
        "unit": None,
    },
    {
        "key": "diag_mp_251",
        "name": "Service Gesamtdaten MP 251",
        "address": "webregler/mp/251/value",
        "unit": None,
    },
    {
        "key": "diag_mp_274",
        "name": "Service Gesamtdaten MP 274",
        "address": "webregler/mp/274/value",
        "unit": None,
    },
    {
        "key": "diag_mp_290",
        "name": "Service Gesamtdaten MP 290",
        "address": "webregler/mp/290/value",
        "unit": None,
    },
    {
        "key": "diag_mp_294",
        "name": "Service Gesamtdaten MP 294",
        "address": "webregler/mp/294/value",
        "unit": None,
    },
    {
        "key": "diag_mp_296",
        "name": "Service Gesamtdaten MP 296",
        "address": "webregler/mp/296/value",
        "unit": None,
    },
    {
        "key": "diag_sp_315",
        "name": "Service Gesamtdaten SP 315",
        "address": "webregler/sp/315/value",
        "unit": None,
    },
    {
        "key": "diag_sp_316",
        "name": "Service Gesamtdaten SP 316",
        "address": "webregler/sp/316/value",
        "unit": None,
    },
    {
        "key": "diag_sp_317",
        "name": "Service Gesamtdaten SP 317",
        "address": "webregler/sp/317/value",
        "unit": None,
    },
    {
        "key": "diag_sp_318",
        "name": "Service Gesamtdaten SP 318",
        "address": "webregler/sp/318/value",
        "unit": None,
    },
    {
        "key": "diag_sp_319",
        "name": "Service Gesamtdaten SP 319",
        "address": "webregler/sp/319/value",
        "unit": None,
    },
    {
        "key": "diag_sp_320",
        "name": "Service Gesamtdaten SP 320",
        "address": "webregler/sp/320/value",
        "unit": None,
    },
    {
        "key": "diag_sp_321",
        "name": "Service Gesamtdaten SP 321",
        "address": "webregler/sp/321/value",
        "unit": None,
    },
    {
        "key": "diag_sp_322",
        "name": "Service Gesamtdaten SP 322",
        "address": "webregler/sp/322/value",
        "unit": None,
    },
    {
        "key": "diag_sp_323",
        "name": "Service Gesamtdaten SP 323",
        "address": "webregler/sp/323/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3235",
        "name": "Service Gesamtdaten SP 3235",
        "address": "webregler/sp/3235/value",
        "unit": None,
    },
    {
        "key": "diag_sp_324",
        "name": "Service Gesamtdaten SP 324",
        "address": "webregler/sp/324/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3243",
        "name": "Service Gesamtdaten SP 3243",
        "address": "webregler/sp/3243/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3246",
        "name": "Service Gesamtdaten SP 3246",
        "address": "webregler/sp/3246/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3248",
        "name": "Service Gesamtdaten SP 3248",
        "address": "webregler/sp/3248/value",
        "unit": None,
    },
    {
        "key": "diag_sp_326",
        "name": "Service Gesamtdaten SP 326",
        "address": "webregler/sp/326/value",
        "unit": None,
    },
    {
        "key": "diag_sp_327",
        "name": "Service Gesamtdaten SP 327",
        "address": "webregler/sp/327/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3275",
        "name": "Service Gesamtdaten SP 3275",
        "address": "webregler/sp/3275/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3276",
        "name": "Service Gesamtdaten SP 3276",
        "address": "webregler/sp/3276/value",
        "unit": None,
    },
    {
        "key": "diag_sp_328",
        "name": "Service Gesamtdaten SP 328",
        "address": "webregler/sp/328/value",
        "unit": None,
    },
    {
        "key": "diag_sp_329",
        "name": "Service Gesamtdaten SP 329",
        "address": "webregler/sp/329/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3292",
        "name": "Service Gesamtdaten SP 3292",
        "address": "webregler/sp/3292/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3295",
        "name": "Service Gesamtdaten SP 3295",
        "address": "webregler/sp/3295/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3296",
        "name": "Service Gesamtdaten SP 3296",
        "address": "webregler/sp/3296/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3297",
        "name": "Service Gesamtdaten SP 3297",
        "address": "webregler/sp/3297/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3298",
        "name": "Service Gesamtdaten SP 3298",
        "address": "webregler/sp/3298/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3299",
        "name": "Service Gesamtdaten SP 3299",
        "address": "webregler/sp/3299/value",
        "unit": None,
    },
    {
        "key": "diag_sp_330",
        "name": "Service Gesamtdaten SP 330",
        "address": "webregler/sp/330/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3300",
        "name": "Service Gesamtdaten SP 3300",
        "address": "webregler/sp/3300/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3301",
        "name": "Service Gesamtdaten SP 3301",
        "address": "webregler/sp/3301/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3303",
        "name": "Service Gesamtdaten SP 3303",
        "address": "webregler/sp/3303/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3304",
        "name": "Service Gesamtdaten SP 3304",
        "address": "webregler/sp/3304/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3305",
        "name": "Service Gesamtdaten SP 3305",
        "address": "webregler/sp/3305/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3306",
        "name": "Service Gesamtdaten SP 3306",
        "address": "webregler/sp/3306/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3309",
        "name": "Service Gesamtdaten SP 3309",
        "address": "webregler/sp/3309/value",
        "unit": None,
    },
    {
        "key": "diag_sp_331",
        "name": "Service Gesamtdaten SP 331",
        "address": "webregler/sp/331/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3310",
        "name": "Service Gesamtdaten SP 3310",
        "address": "webregler/sp/3310/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3311",
        "name": "Service Gesamtdaten SP 3311",
        "address": "webregler/sp/3311/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3312",
        "name": "Service Gesamtdaten SP 3312",
        "address": "webregler/sp/3312/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3313",
        "name": "Service Gesamtdaten SP 3313",
        "address": "webregler/sp/3313/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3314",
        "name": "Service Gesamtdaten SP 3314",
        "address": "webregler/sp/3314/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3316",
        "name": "Service Gesamtdaten SP 3316",
        "address": "webregler/sp/3316/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3317",
        "name": "Service Gesamtdaten SP 3317",
        "address": "webregler/sp/3317/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3318",
        "name": "Service Gesamtdaten SP 3318",
        "address": "webregler/sp/3318/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3319",
        "name": "Service Gesamtdaten SP 3319",
        "address": "webregler/sp/3319/value",
        "unit": None,
    },
    {
        "key": "diag_sp_332",
        "name": "Service Gesamtdaten SP 332",
        "address": "webregler/sp/332/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3320",
        "name": "Service Gesamtdaten SP 3320",
        "address": "webregler/sp/3320/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3327",
        "name": "Service Gesamtdaten SP 3327",
        "address": "webregler/sp/3327/value",
        "unit": None,
    },
    {
        "key": "diag_sp_333",
        "name": "Service Gesamtdaten SP 333",
        "address": "webregler/sp/333/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3333",
        "name": "Service Gesamtdaten SP 3333",
        "address": "webregler/sp/3333/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3334",
        "name": "Service Gesamtdaten SP 3334",
        "address": "webregler/sp/3334/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3335",
        "name": "Service Gesamtdaten SP 3335",
        "address": "webregler/sp/3335/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3336",
        "name": "Service Gesamtdaten SP 3336",
        "address": "webregler/sp/3336/value",
        "unit": None,
    },
    {
        "key": "diag_sp_334",
        "name": "Service Gesamtdaten SP 334",
        "address": "webregler/sp/334/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3344",
        "name": "Service Gesamtdaten SP 3344",
        "address": "webregler/sp/3344/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3345",
        "name": "Service Gesamtdaten SP 3345",
        "address": "webregler/sp/3345/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3346",
        "name": "Service Gesamtdaten SP 3346",
        "address": "webregler/sp/3346/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3349",
        "name": "Service Gesamtdaten SP 3349",
        "address": "webregler/sp/3349/value",
        "unit": None,
    },
    {
        "key": "diag_sp_335",
        "name": "Service Gesamtdaten SP 335",
        "address": "webregler/sp/335/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3353",
        "name": "Service Gesamtdaten SP 3353",
        "address": "webregler/sp/3353/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3356",
        "name": "Service Gesamtdaten SP 3356",
        "address": "webregler/sp/3356/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3357",
        "name": "Service Gesamtdaten SP 3357",
        "address": "webregler/sp/3357/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3358",
        "name": "Service Gesamtdaten SP 3358",
        "address": "webregler/sp/3358/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3359",
        "name": "Service Gesamtdaten SP 3359",
        "address": "webregler/sp/3359/value",
        "unit": None,
    },
    {
        "key": "diag_sp_336",
        "name": "Service Gesamtdaten SP 336",
        "address": "webregler/sp/336/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3367",
        "name": "Service Gesamtdaten SP 3367",
        "address": "webregler/sp/3367/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3368",
        "name": "Service Gesamtdaten SP 3368",
        "address": "webregler/sp/3368/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3369",
        "name": "Service Gesamtdaten SP 3369",
        "address": "webregler/sp/3369/value",
        "unit": None,
    },
    {
        "key": "diag_sp_338",
        "name": "Service Gesamtdaten SP 338",
        "address": "webregler/sp/338/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3385",
        "name": "Service Gesamtdaten SP 3385",
        "address": "webregler/sp/3385/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3389",
        "name": "Service Gesamtdaten SP 3389",
        "address": "webregler/sp/3389/value",
        "unit": None,
    },
    {
        "key": "diag_sp_339",
        "name": "Service Gesamtdaten SP 339",
        "address": "webregler/sp/339/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3390",
        "name": "Service Gesamtdaten SP 3390",
        "address": "webregler/sp/3390/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3391",
        "name": "Service Gesamtdaten SP 3391",
        "address": "webregler/sp/3391/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3392",
        "name": "Service Gesamtdaten SP 3392",
        "address": "webregler/sp/3392/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3393",
        "name": "Service Gesamtdaten SP 3393",
        "address": "webregler/sp/3393/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3394",
        "name": "Service Gesamtdaten SP 3394",
        "address": "webregler/sp/3394/value",
        "unit": None,
    },
    {
        "key": "diag_sp_340",
        "name": "Service Gesamtdaten SP 340",
        "address": "webregler/sp/340/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3405",
        "name": "Service Gesamtdaten SP 3405",
        "address": "webregler/sp/3405/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3406",
        "name": "Service Gesamtdaten SP 3406",
        "address": "webregler/sp/3406/value",
        "unit": None,
    },
    {
        "key": "diag_sp_341",
        "name": "Service Gesamtdaten SP 341",
        "address": "webregler/sp/341/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3416",
        "name": "Service Gesamtdaten SP 3416",
        "address": "webregler/sp/3416/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3417",
        "name": "Service Gesamtdaten SP 3417",
        "address": "webregler/sp/3417/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3419",
        "name": "Service Gesamtdaten SP 3419",
        "address": "webregler/sp/3419/value",
        "unit": None,
    },
    {
        "key": "diag_sp_342",
        "name": "Service Gesamtdaten SP 342",
        "address": "webregler/sp/342/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3420",
        "name": "Service Gesamtdaten SP 3420",
        "address": "webregler/sp/3420/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3421",
        "name": "Service Gesamtdaten SP 3421",
        "address": "webregler/sp/3421/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3422",
        "name": "Service Gesamtdaten SP 3422",
        "address": "webregler/sp/3422/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3423",
        "name": "Service Gesamtdaten SP 3423",
        "address": "webregler/sp/3423/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3426",
        "name": "Service Gesamtdaten SP 3426",
        "address": "webregler/sp/3426/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3427",
        "name": "Service Gesamtdaten SP 3427",
        "address": "webregler/sp/3427/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3429",
        "name": "Service Gesamtdaten SP 3429",
        "address": "webregler/sp/3429/value",
        "unit": None,
    },
    {
        "key": "diag_sp_343",
        "name": "Service Gesamtdaten SP 343",
        "address": "webregler/sp/343/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3430",
        "name": "Service Gesamtdaten SP 3430",
        "address": "webregler/sp/3430/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3439",
        "name": "Service Gesamtdaten SP 3439",
        "address": "webregler/sp/3439/value",
        "unit": None,
    },
    {
        "key": "diag_sp_344",
        "name": "Service Gesamtdaten SP 344",
        "address": "webregler/sp/344/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3440",
        "name": "Service Gesamtdaten SP 3440",
        "address": "webregler/sp/3440/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3441",
        "name": "Service Gesamtdaten SP 3441",
        "address": "webregler/sp/3441/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3442",
        "name": "Service Gesamtdaten SP 3442",
        "address": "webregler/sp/3442/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3443",
        "name": "Service Gesamtdaten SP 3443",
        "address": "webregler/sp/3443/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3446",
        "name": "Service Gesamtdaten SP 3446",
        "address": "webregler/sp/3446/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3447",
        "name": "Service Gesamtdaten SP 3447",
        "address": "webregler/sp/3447/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3448",
        "name": "Service Gesamtdaten SP 3448",
        "address": "webregler/sp/3448/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3449",
        "name": "Service Gesamtdaten SP 3449",
        "address": "webregler/sp/3449/value",
        "unit": None,
    },
    {
        "key": "diag_sp_345",
        "name": "Service Gesamtdaten SP 345",
        "address": "webregler/sp/345/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3450",
        "name": "Service Gesamtdaten SP 3450",
        "address": "webregler/sp/3450/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3451",
        "name": "Service Gesamtdaten SP 3451",
        "address": "webregler/sp/3451/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3457",
        "name": "Service Gesamtdaten SP 3457",
        "address": "webregler/sp/3457/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3459",
        "name": "Service Gesamtdaten SP 3459",
        "address": "webregler/sp/3459/value",
        "unit": None,
    },
    {
        "key": "diag_sp_346",
        "name": "Service Gesamtdaten SP 346",
        "address": "webregler/sp/346/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3460",
        "name": "Service Gesamtdaten SP 3460",
        "address": "webregler/sp/3460/value",
        "unit": None,
    },
    {
        "key": "diag_sp_347",
        "name": "Service Gesamtdaten WW Normal Max",
        "address": "webregler/sp/347/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_mcg_web_machinetype",
        "name": "Service Grundbedienung Maschinentyp",
        "address": "mcg/data/web/machineType",
        "unit": None,
    },
    {
        "key": "diag_mcg_version",
        "name": "Service Grundbedienung RCG Version",
        "address": "mcg/data/version",
        "unit": None,
    },
    {
        "key": "diag_sp_311",
        "name": "Service Grundbedienung SP 311",
        "address": "webregler/sp/311/value",
        "unit": None,
    },
    {
        "key": "diag_mcg_web_serialnr",
        "name": "Service Grundbedienung Seriennummer",
        "address": "mcg/data/web/serialnr",
        "unit": None,
    },
    {
        "key": "diag_mcg_srvversion",
        "name": "Service Grundbedienung Service Version",
        "address": "mcg/data/srvVersion",
        "unit": None,
    },
    {
        "key": "diag_mcg_web_version",
        "name": "Service Grundbedienung WebRegler Version",
        "address": "mcg/data/web/version",
        "unit": None,
    },
    {
        "key": "diag_mcg_webclientversion",
        "name": "Service Grundbedienung Webclient Version",
        "address": "mcg/data/webclientversion",
        "unit": None,
    },
    {
        "key": "diag_sp_3181",
        "name": "Service Heizkreis SP 3181",
        "address": "webregler/sp/3181/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3182",
        "name": "Service Heizkreis SP 3182",
        "address": "webregler/sp/3182/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3256",
        "name": "Service Heizkreis SP 3256",
        "address": "webregler/sp/3256/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3351",
        "name": "Service Heizkreis SP 3351",
        "address": "webregler/sp/3351/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3437",
        "name": "Service Heizkreis SP 3437",
        "address": "webregler/sp/3437/value",
        "unit": None,
    },
    {
        "key": "diag_sp_369",
        "name": "Service Heizkreis SP 369",
        "address": "webregler/sp/369/value",
        "unit": None,
    },
    {
        "key": "diag_sp_371",
        "name": "Service Heizkreis SP 371",
        "address": "webregler/sp/371/value",
        "unit": None,
    },
    {
        "key": "diag_sp_372",
        "name": "Service Heizkreis SP 372",
        "address": "webregler/sp/372/value",
        "unit": None,
    },
    {
        "key": "diag_sp_373",
        "name": "Service Heizkreis SP 373",
        "address": "webregler/sp/373/value",
        "unit": None,
    },
    {
        "key": "diag_sp_374",
        "name": "Service Heizkreis SP 374",
        "address": "webregler/sp/374/value",
        "unit": None,
    },
    {
        "key": "diag_sp_375",
        "name": "Service Heizkreis SP 375",
        "address": "webregler/sp/375/value",
        "unit": None,
    },
    {
        "key": "diag_sp_377",
        "name": "Service Heizkreis SP 377",
        "address": "webregler/sp/377/value",
        "unit": None,
    },
    {
        "key": "diag_sp_378",
        "name": "Service Heizkreis SP 378",
        "address": "webregler/sp/378/value",
        "unit": None,
    },
    {
        "key": "diag_sp_379",
        "name": "Service Heizkreis SP 379",
        "address": "webregler/sp/379/value",
        "unit": None,
    },
    {
        "key": "diag_sp_380",
        "name": "Service Heizkreis SP 380",
        "address": "webregler/sp/380/value",
        "unit": None,
    },
    {
        "key": "diag_sp_381",
        "name": "Service Heizkreis SP 381",
        "address": "webregler/sp/381/value",
        "unit": None,
    },
    {
        "key": "diag_sp_382",
        "name": "Service Heizkreis SP 382",
        "address": "webregler/sp/382/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3199",
        "name": "Service Main SP 3199",
        "address": "webregler/sp/3199/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3222",
        "name": "Service Main SP 3222",
        "address": "webregler/sp/3222/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3271",
        "name": "Service Main SP 3271",
        "address": "webregler/sp/3271/value",
        "unit": None,
    },
    {
        "key": "diag_sp_35",
        "name": "Service Main SP 35",
        "address": "webregler/sp/35/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3200",
        "name": "Service Mischer1 SP 3200",
        "address": "webregler/sp/3200/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3202",
        "name": "Service Mischer1 SP 3202",
        "address": "webregler/sp/3202/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3203",
        "name": "Service Mischer1 SP 3203",
        "address": "webregler/sp/3203/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3204",
        "name": "Service Mischer1 SP 3204",
        "address": "webregler/sp/3204/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3206",
        "name": "Service Mischer1 SP 3206",
        "address": "webregler/sp/3206/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3207",
        "name": "Service Mischer1 SP 3207",
        "address": "webregler/sp/3207/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3208",
        "name": "Service Mischer1 SP 3208",
        "address": "webregler/sp/3208/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3209",
        "name": "Service Mischer1 SP 3209",
        "address": "webregler/sp/3209/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3210",
        "name": "Service Mischer1 SP 3210",
        "address": "webregler/sp/3210/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3211",
        "name": "Service Mischer1 SP 3211",
        "address": "webregler/sp/3211/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3213",
        "name": "Service Mischer1 SP 3213",
        "address": "webregler/sp/3213/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3214",
        "name": "Service Mischer1 SP 3214",
        "address": "webregler/sp/3214/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3215",
        "name": "Service Mischer1 SP 3215",
        "address": "webregler/sp/3215/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3216",
        "name": "Service Mischer1 SP 3216",
        "address": "webregler/sp/3216/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3217",
        "name": "Service Mischer1 SP 3217",
        "address": "webregler/sp/3217/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3218",
        "name": "Service Mischer1 SP 3218",
        "address": "webregler/sp/3218/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3221",
        "name": "Service Mischer1 SP 3221",
        "address": "webregler/sp/3221/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3453",
        "name": "Service Mischer1 SP 3453",
        "address": "webregler/sp/3453/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3223",
        "name": "Service Mischer2 SP 3223",
        "address": "webregler/sp/3223/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3225",
        "name": "Service Mischer2 SP 3225",
        "address": "webregler/sp/3225/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3226",
        "name": "Service Mischer2 SP 3226",
        "address": "webregler/sp/3226/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3227",
        "name": "Service Mischer2 SP 3227",
        "address": "webregler/sp/3227/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3228",
        "name": "Service Mischer2 SP 3228",
        "address": "webregler/sp/3228/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3229",
        "name": "Service Mischer2 SP 3229",
        "address": "webregler/sp/3229/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3230",
        "name": "Service Mischer2 SP 3230",
        "address": "webregler/sp/3230/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3231",
        "name": "Service Mischer2 SP 3231",
        "address": "webregler/sp/3231/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3232",
        "name": "Service Mischer2 SP 3232",
        "address": "webregler/sp/3232/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3233",
        "name": "Service Mischer2 SP 3233",
        "address": "webregler/sp/3233/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3234",
        "name": "Service Mischer2 SP 3234",
        "address": "webregler/sp/3234/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3236",
        "name": "Service Mischer2 SP 3236",
        "address": "webregler/sp/3236/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3237",
        "name": "Service Mischer2 SP 3237",
        "address": "webregler/sp/3237/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3238",
        "name": "Service Mischer2 SP 3238",
        "address": "webregler/sp/3238/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3239",
        "name": "Service Mischer2 SP 3239",
        "address": "webregler/sp/3239/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3240",
        "name": "Service Mischer2 SP 3240",
        "address": "webregler/sp/3240/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3241",
        "name": "Service Mischer2 SP 3241",
        "address": "webregler/sp/3241/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3244",
        "name": "Service Mischer2 SP 3244",
        "address": "webregler/sp/3244/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3355",
        "name": "Service Mischer2 SP 3355",
        "address": "webregler/sp/3355/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3455",
        "name": "Service Mischer2 SP 3455",
        "address": "webregler/sp/3455/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3249",
        "name": "Service Party SP 3249",
        "address": "webregler/sp/3249/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3250",
        "name": "Service Party SP 3250",
        "address": "webregler/sp/3250/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3251",
        "name": "Service Party SP 3251",
        "address": "webregler/sp/3251/value",
        "unit": None,
    },
    {
        "key": "diag_mp_212",
        "name": "Service Sicherheitskette MP 212",
        "address": "webregler/mp/212/value",
        "unit": None,
    },
    {
        "key": "diag_mp_213",
        "name": "Service Sicherheitskette MP 213",
        "address": "webregler/mp/213/value",
        "unit": None,
    },
    {
        "key": "diag_mp_220",
        "name": "Service Sicherheitskette MP 220",
        "address": "webregler/mp/220/value",
        "unit": None,
    },
    {
        "key": "diag_mp_221",
        "name": "Service Sicherheitskette MP 221",
        "address": "webregler/mp/221/value",
        "unit": None,
    },
    {
        "key": "diag_mp_261",
        "name": "Service Sicherheitskette MP 261",
        "address": "webregler/mp/261/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3100",
        "name": "Service Sicherheitskette SP 3100",
        "address": "webregler/sp/3100/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3101",
        "name": "Service Sicherheitskette SP 3101",
        "address": "webregler/sp/3101/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3102",
        "name": "Service Sicherheitskette SP 3102",
        "address": "webregler/sp/3102/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3103",
        "name": "Service Sicherheitskette SP 3103",
        "address": "webregler/sp/3103/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3104",
        "name": "Service Sicherheitskette SP 3104",
        "address": "webregler/sp/3104/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3105",
        "name": "Service Sicherheitskette SP 3105",
        "address": "webregler/sp/3105/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3106",
        "name": "Service Sicherheitskette SP 3106",
        "address": "webregler/sp/3106/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3107",
        "name": "Service Sicherheitskette SP 3107",
        "address": "webregler/sp/3107/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3108",
        "name": "Service Sicherheitskette SP 3108",
        "address": "webregler/sp/3108/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3109",
        "name": "Service Sicherheitskette SP 3109",
        "address": "webregler/sp/3109/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3110",
        "name": "Service Sicherheitskette SP 3110",
        "address": "webregler/sp/3110/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3111",
        "name": "Service Sicherheitskette SP 3111",
        "address": "webregler/sp/3111/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3112",
        "name": "Service Sicherheitskette SP 3112",
        "address": "webregler/sp/3112/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3113",
        "name": "Service Sicherheitskette SP 3113",
        "address": "webregler/sp/3113/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3114",
        "name": "Service Sicherheitskette SP 3114",
        "address": "webregler/sp/3114/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3115",
        "name": "Service Sicherheitskette SP 3115",
        "address": "webregler/sp/3115/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3116",
        "name": "Service Sicherheitskette SP 3116",
        "address": "webregler/sp/3116/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3117",
        "name": "Service Sicherheitskette SP 3117",
        "address": "webregler/sp/3117/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3118",
        "name": "Service Sicherheitskette SP 3118",
        "address": "webregler/sp/3118/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3119",
        "name": "Service Sicherheitskette SP 3119",
        "address": "webregler/sp/3119/value",
        "unit": None,
    },
    {
        "key": "diag_sp_312",
        "name": "Service Sicherheitskette SP 312",
        "address": "webregler/sp/312/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3121",
        "name": "Service Sicherheitskette SP 3121",
        "address": "webregler/sp/3121/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3122",
        "name": "Service Sicherheitskette SP 3122",
        "address": "webregler/sp/3122/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3123",
        "name": "Service Sicherheitskette SP 3123",
        "address": "webregler/sp/3123/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3124",
        "name": "Service Sicherheitskette SP 3124",
        "address": "webregler/sp/3124/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3125",
        "name": "Service Sicherheitskette SP 3125",
        "address": "webregler/sp/3125/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3126",
        "name": "Service Sicherheitskette SP 3126",
        "address": "webregler/sp/3126/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3127",
        "name": "Service Sicherheitskette SP 3127",
        "address": "webregler/sp/3127/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3128",
        "name": "Service Sicherheitskette SP 3128",
        "address": "webregler/sp/3128/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3129",
        "name": "Service Sicherheitskette SP 3129",
        "address": "webregler/sp/3129/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3130",
        "name": "Service Sicherheitskette SP 3130",
        "address": "webregler/sp/3130/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3131",
        "name": "Service Sicherheitskette SP 3131",
        "address": "webregler/sp/3131/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3132",
        "name": "Service Sicherheitskette SP 3132",
        "address": "webregler/sp/3132/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3133",
        "name": "Service Sicherheitskette SP 3133",
        "address": "webregler/sp/3133/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3134",
        "name": "Service Sicherheitskette SP 3134",
        "address": "webregler/sp/3134/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3135",
        "name": "Service Sicherheitskette SP 3135",
        "address": "webregler/sp/3135/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3136",
        "name": "Service Sicherheitskette SP 3136",
        "address": "webregler/sp/3136/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3137",
        "name": "Service Sicherheitskette SP 3137",
        "address": "webregler/sp/3137/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3138",
        "name": "Service Sicherheitskette SP 3138",
        "address": "webregler/sp/3138/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3139",
        "name": "Service Sicherheitskette SP 3139",
        "address": "webregler/sp/3139/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3140",
        "name": "Service Sicherheitskette SP 3140",
        "address": "webregler/sp/3140/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3142",
        "name": "Service Sicherheitskette SP 3142",
        "address": "webregler/sp/3142/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3143",
        "name": "Service Sicherheitskette SP 3143",
        "address": "webregler/sp/3143/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3145",
        "name": "Service Sicherheitskette SP 3145",
        "address": "webregler/sp/3145/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3146",
        "name": "Service Sicherheitskette SP 3146",
        "address": "webregler/sp/3146/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3148",
        "name": "Service Sicherheitskette SP 3148",
        "address": "webregler/sp/3148/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3190",
        "name": "Service Sicherheitskette SP 3190",
        "address": "webregler/sp/3190/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3191",
        "name": "Service Sicherheitskette SP 3191",
        "address": "webregler/sp/3191/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3192",
        "name": "Service Sicherheitskette SP 3192",
        "address": "webregler/sp/3192/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3193",
        "name": "Service Sicherheitskette SP 3193",
        "address": "webregler/sp/3193/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3194",
        "name": "Service Sicherheitskette SP 3194",
        "address": "webregler/sp/3194/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3195",
        "name": "Service Sicherheitskette SP 3195",
        "address": "webregler/sp/3195/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3196",
        "name": "Service Sicherheitskette SP 3196",
        "address": "webregler/sp/3196/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3197",
        "name": "Service Sicherheitskette SP 3197",
        "address": "webregler/sp/3197/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3198",
        "name": "Service Sicherheitskette SP 3198",
        "address": "webregler/sp/3198/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3255",
        "name": "Service Sicherheitskette SP 3255",
        "address": "webregler/sp/3255/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3258",
        "name": "Service Sicherheitskette SP 3258",
        "address": "webregler/sp/3258/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3259",
        "name": "Service Sicherheitskette SP 3259",
        "address": "webregler/sp/3259/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3260",
        "name": "Service Sicherheitskette SP 3260",
        "address": "webregler/sp/3260/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3261",
        "name": "Service Sicherheitskette SP 3261",
        "address": "webregler/sp/3261/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3262",
        "name": "Service Sicherheitskette SP 3262",
        "address": "webregler/sp/3262/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3302",
        "name": "Service Sicherheitskette SP 3302",
        "address": "webregler/sp/3302/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3307",
        "name": "Service Sicherheitskette SP 3307",
        "address": "webregler/sp/3307/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3308",
        "name": "Service Sicherheitskette SP 3308",
        "address": "webregler/sp/3308/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3326",
        "name": "Service Sicherheitskette SP 3326",
        "address": "webregler/sp/3326/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3337",
        "name": "Service Sicherheitskette SP 3337",
        "address": "webregler/sp/3337/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3338",
        "name": "Service Sicherheitskette SP 3338",
        "address": "webregler/sp/3338/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3382",
        "name": "Service Sicherheitskette SP 3382",
        "address": "webregler/sp/3382/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3383",
        "name": "Service Sicherheitskette SP 3383",
        "address": "webregler/sp/3383/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3384",
        "name": "Service Sicherheitskette SP 3384",
        "address": "webregler/sp/3384/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3386",
        "name": "Service Sicherheitskette SP 3386",
        "address": "webregler/sp/3386/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3387",
        "name": "Service Sicherheitskette SP 3387",
        "address": "webregler/sp/3387/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3444",
        "name": "Service Sicherheitskette SP 3444",
        "address": "webregler/sp/3444/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3445",
        "name": "Service Sicherheitskette SP 3445",
        "address": "webregler/sp/3445/value",
        "unit": None,
    },
    {
        "key": "diag_sp_394",
        "name": "Service Sicherheitskette SP 394",
        "address": "webregler/sp/394/value",
        "unit": None,
    },
    {
        "key": "diag_sp_395",
        "name": "Service Sicherheitskette SP 395",
        "address": "webregler/sp/395/value",
        "unit": None,
    },
    {
        "key": "diag_sp_396",
        "name": "Service Sicherheitskette SP 396",
        "address": "webregler/sp/396/value",
        "unit": None,
    },
    {
        "key": "diag_sp_397",
        "name": "Service Sicherheitskette SP 397",
        "address": "webregler/sp/397/value",
        "unit": None,
    },
    {
        "key": "diag_sp_398",
        "name": "Service Sicherheitskette SP 398",
        "address": "webregler/sp/398/value",
        "unit": None,
    },
    {
        "key": "diag_sp_399",
        "name": "Service Sicherheitskette SP 399",
        "address": "webregler/sp/399/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3152",
        "name": "Service Solaranlage SP 3152",
        "address": "webregler/sp/3152/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3272",
        "name": "Service Solaranlage SP 3272",
        "address": "webregler/sp/3272/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3273",
        "name": "Service Solaranlage SP 3273",
        "address": "webregler/sp/3273/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3274",
        "name": "Service Solaranlage SP 3274",
        "address": "webregler/sp/3274/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3283",
        "name": "Service Solaranlage SP 3283",
        "address": "webregler/sp/3283/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3284",
        "name": "Service Solaranlage SP 3284",
        "address": "webregler/sp/3284/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3285",
        "name": "Service Solaranlage SP 3285",
        "address": "webregler/sp/3285/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3332",
        "name": "Service Solaranlage SP 3332",
        "address": "webregler/sp/3332/value",
        "unit": None,
    },
    {
        "key": "diag_sp_352",
        "name": "Service WNA MKR2 min Ruecklauftemperatur Kuehlen",
        "address": "webregler/sp/352/value",
        "unit": 'celsius',
    },
    {
        "key": "diag_sp_3141",
        "name": "Service WNA SP 3141",
        "address": "webregler/sp/3141/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3147",
        "name": "Service WNA SP 3147",
        "address": "webregler/sp/3147/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3263",
        "name": "Service WNA SP 3263",
        "address": "webregler/sp/3263/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3264",
        "name": "Service WNA SP 3264",
        "address": "webregler/sp/3264/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3267",
        "name": "Service WNA SP 3267",
        "address": "webregler/sp/3267/value",
        "unit": None,
    },
    {
        "key": "diag_sp_33",
        "name": "Service WNA SP 33",
        "address": "webregler/sp/33/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3315",
        "name": "Service WNA SP 3315",
        "address": "webregler/sp/3315/value",
        "unit": None,
    },
    {
        "key": "diag_sp_34",
        "name": "Service WNA SP 34",
        "address": "webregler/sp/34/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3402",
        "name": "Service WNA SP 3402",
        "address": "webregler/sp/3402/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3403",
        "name": "Service WNA SP 3403",
        "address": "webregler/sp/3403/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3428",
        "name": "Service WNA SP 3428",
        "address": "webregler/sp/3428/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3458",
        "name": "Service WNA SP 3458",
        "address": "webregler/sp/3458/value",
        "unit": None,
    },
    {
        "key": "diag_sp_353",
        "name": "Service WNA SP 353",
        "address": "webregler/sp/353/value",
        "unit": None,
    },
    {
        "key": "diag_sp_36",
        "name": "Service WNA SP 36",
        "address": "webregler/sp/36/value",
        "unit": None,
    },
    {
        "key": "diag_sp_37",
        "name": "Service WNA SP 37",
        "address": "webregler/sp/37/value",
        "unit": None,
    },
    {
        "key": "diag_sp_38",
        "name": "Service WNA SP 38",
        "address": "webregler/sp/38/value",
        "unit": None,
    },
    {
        "key": "diag_mp_2103",
        "name": "Service Warmwasser MP 2103",
        "address": "webregler/mp/2103/value",
        "unit": None,
    },
    {
        "key": "diag_mp_238",
        "name": "Service Warmwasser MP 238",
        "address": "webregler/mp/238/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3339",
        "name": "Service Warmwasser SP 3339",
        "address": "webregler/sp/3339/value",
        "unit": None,
    },
    {
        "key": "diag_sp_3347",
        "name": "Service Warmwasser SP 3347",
        "address": "webregler/sp/3347/value",
        "unit": None,
    },
    {
        "key": "diag_sp_349",
        "name": "Service Warmwasser SP 349",
        "address": "webregler/sp/349/value",
        "unit": None,
    },
    {
        "key": "diag_sp_350",
        "name": "Service Warmwasser SP 350",
        "address": "webregler/sp/350/value",
        "unit": None,
    },
    {
        "key": "diag_sp_351",
        "name": "Service Warmwasser SP 351",
        "address": "webregler/sp/351/value",
        "unit": None,
    },
    {
        "key": "diag_sp_370",
        "name": "Service Warmwasser SP 370",
        "address": "webregler/sp/370/value",
        "unit": None,
    },
    {
        "key": "diag_sp_383",
        "name": "Service Warmwasser SP 383",
        "address": "webregler/sp/383/value",
        "unit": None,
    },
    {
        "key": "diag_sp_384",
        "name": "Service Warmwasser SP 384",
        "address": "webregler/sp/384/value",
        "unit": None,
    },
    {
        "key": "diag_sp_385",
        "name": "Service Warmwasser SP 385",
        "address": "webregler/sp/385/value",
        "unit": None,
    },
    {
        "key": "diag_sp_386",
        "name": "Service Warmwasser SP 386",
        "address": "webregler/sp/386/value",
        "unit": None,
    },
    {
        "key": "diag_sp_387",
        "name": "Service Warmwasser SP 387",
        "address": "webregler/sp/387/value",
        "unit": None,
    },
    {
        "key": "diag_sp_388",
        "name": "Service Warmwasser SP 388",
        "address": "webregler/sp/388/value",
        "unit": None,
    },
    {
        "key": "diag_sp_389",
        "name": "Service Warmwasser SP 389",
        "address": "webregler/sp/389/value",
        "unit": None,
    },
    {
        "key": "diag_sp_390",
        "name": "Service Warmwasser SP 390",
        "address": "webregler/sp/390/value",
        "unit": None,
    },
    {
        "key": "diag_sp_391",
        "name": "Service Warmwasser SP 391",
        "address": "webregler/sp/391/value",
        "unit": None,
    },
    {
        "key": "diag_sp_392",
        "name": "Service Warmwasser SP 392",
        "address": "webregler/sp/392/value",
        "unit": None,
    },
    {
        "key": "diag_sp_393",
        "name": "Service Warmwasser SP 393",
        "address": "webregler/sp/393/value",
        "unit": None,
    },
)
